// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

// COMPONENT Cargear

lv_obj_t * ui_Cargear_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Cargear;
    cui_Cargear = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Cargear);
    lv_obj_set_width(cui_Cargear, 316);
    lv_obj_set_height(cui_Cargear, 20);
    lv_obj_set_x(cui_Cargear, 3);
    lv_obj_set_y(cui_Cargear, 3);
    lv_obj_clear_flag(cui_Cargear, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label_R;
    cui_Label_R = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Label_R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_R, -130);
    lv_obj_set_y(cui_Label_R, 1);
    lv_obj_set_align(cui_Label_R, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_R, "R");
    lv_obj_set_style_text_color(cui_Label_R, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_R, &ui_font_google_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_P;
    cui_Label_P = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Label_P, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_P, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_P, -147);
    lv_obj_set_y(cui_Label_P, 1);
    lv_obj_set_align(cui_Label_P, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_P, "P");
    lv_obj_set_style_text_color(cui_Label_P, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_P, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_P, &ui_font_google_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_N;
    cui_Label_N = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Label_N, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_N, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_N, -111);
    lv_obj_set_y(cui_Label_N, 1);
    lv_obj_set_align(cui_Label_N, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_N, "N");
    lv_obj_set_style_text_color(cui_Label_N, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_N, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_N, &ui_font_google_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_D;
    cui_Label_D = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Label_D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_D, -91);
    lv_obj_set_y(cui_Label_D, 1);
    lv_obj_set_align(cui_Label_D, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_D, "D");
    lv_obj_set_style_text_color(cui_Label_D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_D, &ui_font_google_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_S;
    cui_Label_S = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Label_S, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_S, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_S, -74);
    lv_obj_set_y(cui_Label_S, 1);
    lv_obj_set_align(cui_Label_S, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_S, "S");
    lv_obj_set_style_text_color(cui_Label_S, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_S, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_S, &ui_font_google_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Power_Bar;
    cui_Power_Bar = lv_bar_create(cui_Cargear);
    lv_bar_set_mode(cui_Power_Bar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(cui_Power_Bar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_Power_Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Power_Bar, 32);
    lv_obj_set_height(cui_Power_Bar, 11);
    lv_obj_set_x(cui_Power_Bar, 103);
    lv_obj_set_y(cui_Power_Bar, 0);
    lv_obj_set_align(cui_Power_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Power_Bar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Power_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Power_Bar, lv_color_hex(0x1FD000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Power_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Power_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Power_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Power_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Power_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Power_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Power_Bar, lv_color_hex(0x00E107), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Power_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Power_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Power_Bar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Power_Bar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Power_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Power_Bar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Power_Bar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t * cui_Power_percent;
    cui_Power_percent = lv_label_create(cui_Cargear);
    lv_obj_set_width(cui_Power_percent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Power_percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Power_percent, -6);
    lv_obj_set_y(cui_Power_percent, 0);
    lv_obj_set_align(cui_Power_percent, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Power_percent, "25%");
    lv_obj_set_style_text_color(cui_Power_percent, lv_color_hex(0x00E200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Power_percent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Power_percent, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CARGEAR_NUM);
    children[UI_COMP_CARGEAR_CARGEAR] = cui_Cargear;
    children[UI_COMP_CARGEAR_LABEL_R] = cui_Label_R;
    children[UI_COMP_CARGEAR_LABEL_P] = cui_Label_P;
    children[UI_COMP_CARGEAR_LABEL_N] = cui_Label_N;
    children[UI_COMP_CARGEAR_LABEL_D] = cui_Label_D;
    children[UI_COMP_CARGEAR_LABEL_S] = cui_Label_S;
    children[UI_COMP_CARGEAR_POWER_BAR] = cui_Power_Bar;
    children[UI_COMP_CARGEAR_POWER_PERCENT] = cui_Power_percent;
    lv_obj_add_event_cb(cui_Cargear, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Cargear, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Cargear_create_hook(cui_Cargear);
    return cui_Cargear;
}

