// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef _UI_COMP_CARGEAR_H
#define _UI_COMP_CARGEAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Cargear
#define UI_COMP_CARGEAR_CARGEAR 0
#define UI_COMP_CARGEAR_LABEL_R 1
#define UI_COMP_CARGEAR_LABEL_P 2
#define UI_COMP_CARGEAR_LABEL_N 3
#define UI_COMP_CARGEAR_LABEL_D 4
#define UI_COMP_CARGEAR_LABEL_S 5
#define UI_COMP_CARGEAR_POWER_BAR 6
#define UI_COMP_CARGEAR_POWER_PERCENT 7
#define _UI_COMP_CARGEAR_NUM 8
lv_obj_t * ui_Cargear_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
