// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_CHARGE_H
#define UI_CHARGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Charge
extern void ui_Charge_screen_init(void);
extern void ui_Charge_screen_destroy(void);
extern lv_obj_t * ui_Charge;
extern lv_obj_t * ui_Charge_line_animation;
extern lv_obj_t * ui_charge_power_animation;
extern lv_obj_t * ui_Charge_Image;
extern lv_obj_t * ui_Charge_Power;
extern lv_obj_t * ui_Charge_Power_Unit;
extern lv_obj_t * ui_Battery_range;
extern lv_obj_t * ui_Battery_range_unit;
extern lv_obj_t * ui_Cargear1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

