// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Door_open = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Door_open_text = NULL;
lv_obj_t * ui_Cargear2 = NULL;
// event funtions

// build funtions

void ui_Door_open_screen_init(void)
{
    ui_Door_open = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Door_open, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Door_open, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Door_open, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Door_open);
    lv_img_set_src(ui_Image1, &ui_img_door_open_3_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Door_open_text = lv_label_create(ui_Door_open);
    lv_obj_set_width(ui_Door_open_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Door_open_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Door_open_text, 0);
    lv_obj_set_y(ui_Door_open_text, 92);
    lv_obj_set_align(ui_Door_open_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Door_open_text, "DOOR OPEN");
    lv_obj_set_style_text_color(ui_Door_open_text, lv_color_hex(0xEE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Door_open_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Door_open_text, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cargear2 = ui_Cargear_create(ui_Door_open);
    lv_obj_set_x(ui_Cargear2, 3);
    lv_obj_set_y(ui_Cargear2, 3);

}

void ui_Door_open_screen_destroy(void)
{
    if(ui_Door_open) lv_obj_del(ui_Door_open);

    // NULL screen variables
    ui_Door_open = NULL;
    ui_Image1 = NULL;
    ui_Door_open_text = NULL;
    ui_Cargear2 = NULL;

}
