// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_DOOR_OPEN_H
#define UI_DOOR_OPEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Door_open
extern void ui_Door_open_screen_init(void);
extern void ui_Door_open_screen_destroy(void);
extern void ui_event_Door_open(lv_event_t * e);
extern lv_obj_t * ui_Door_open;
extern lv_obj_t * ui_Door_open_text;
extern lv_obj_t * ui_door_open_img;
extern lv_obj_t * ui_Cargear2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

