// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_DRIVE_H
#define UI_DRIVE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Drive
extern void ui_Drive_screen_init(void);
extern void ui_Drive_screen_destroy(void);
extern void ui_event_Drive(lv_event_t * e);
extern lv_obj_t * ui_Drive;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Speed_Label;
extern lv_obj_t * ui_Speed_Unit;
extern lv_obj_t * ui_FSD_icon;
extern lv_obj_t * ui_Cargear;
extern lv_obj_t * ui_Tire_pressure;
extern lv_obj_t * ui_Tire_Image;
extern lv_obj_t * ui_Tire_right_front;
extern lv_obj_t * ui_Tire_right_back;
extern lv_obj_t * ui_Tire_left_front;
extern lv_obj_t * ui_Tire_left_back;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Inside_Temp;
extern lv_obj_t * ui_Outside_Temp;
extern lv_obj_t * ui_Power_Save_Bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

