// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Drive = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_Speed_Label = NULL;
lv_obj_t * ui_Speed_Unit = NULL;
lv_obj_t * ui_FSD_icon = NULL;
lv_obj_t * ui_Cargear = NULL;
lv_obj_t * ui_Tire_pressure = NULL;
lv_obj_t * ui_Tire_Image = NULL;
lv_obj_t * ui_Tire_right_front = NULL;
lv_obj_t * ui_Tire_right_back = NULL;
lv_obj_t * ui_Tire_left_front = NULL;
lv_obj_t * ui_Tire_left_back = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Inside_Temp = NULL;
lv_obj_t * ui_Outside_Temp = NULL;
lv_obj_t * ui_Power_Save_Bar = NULL;
// event funtions

// build funtions

void ui_Drive_screen_init(void)
{
    ui_Drive = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Drive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Drive, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Drive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed = lv_obj_create(ui_Drive);
    lv_obj_remove_style_all(ui_Speed);
    lv_obj_set_width(ui_Speed, 187);
    lv_obj_set_height(ui_Speed, 111);
    lv_obj_set_x(ui_Speed, 0);
    lv_obj_set_y(ui_Speed, -10);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed_Label = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_Speed_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Speed_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed_Label, "56");
    lv_obj_set_style_text_color(ui_Speed_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed_Label, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed_Unit = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_Speed_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed_Unit, 0);
    lv_obj_set_y(ui_Speed_Unit, 52);
    lv_obj_set_align(ui_Speed_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed_Unit, "KM/H");
    lv_obj_set_style_text_color(ui_Speed_Unit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSD_icon = lv_img_create(ui_Drive);
    lv_img_set_src(ui_FSD_icon, &ui_img_fsd_png);
    lv_obj_set_width(ui_FSD_icon, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_FSD_icon, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_FSD_icon, 0);
    lv_obj_set_y(ui_FSD_icon, 91);
    lv_obj_set_align(ui_FSD_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FSD_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FSD_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cargear = ui_Cargear_create(ui_Drive);
    lv_obj_set_x(ui_Cargear, 3);
    lv_obj_set_y(ui_Cargear, 3);

    ui_Tire_pressure = lv_obj_create(ui_Drive);
    lv_obj_remove_style_all(ui_Tire_pressure);
    lv_obj_set_width(ui_Tire_pressure, 100);
    lv_obj_set_height(ui_Tire_pressure, 50);
    lv_obj_set_x(ui_Tire_pressure, -106);
    lv_obj_set_y(ui_Tire_pressure, 91);
    lv_obj_set_align(ui_Tire_pressure, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tire_pressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tire_Image = lv_img_create(ui_Tire_pressure);
    lv_img_set_src(ui_Tire_Image, &ui_img_car1_png);
    lv_obj_set_width(ui_Tire_Image, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_Tire_Image, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Tire_Image, 1);
    lv_obj_set_y(ui_Tire_Image, -2);
    lv_obj_set_align(ui_Tire_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tire_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Tire_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tire_right_front = lv_label_create(ui_Tire_pressure);
    lv_obj_set_width(ui_Tire_right_front, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tire_right_front, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tire_right_front, 72);
    lv_obj_set_y(ui_Tire_right_front, -14);
    lv_obj_set_align(ui_Tire_right_front, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Tire_right_front, "2.9");
    lv_obj_set_style_text_color(ui_Tire_right_front, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tire_right_front, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tire_right_front, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tire_right_back = lv_label_create(ui_Tire_pressure);
    lv_obj_set_width(ui_Tire_right_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tire_right_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tire_right_back, 72);
    lv_obj_set_y(ui_Tire_right_back, 10);
    lv_obj_set_align(ui_Tire_right_back, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Tire_right_back, "2.9");
    lv_obj_set_style_text_color(ui_Tire_right_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tire_right_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tire_right_back, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tire_left_front = lv_label_create(ui_Tire_pressure);
    lv_obj_set_width(ui_Tire_left_front, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tire_left_front, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tire_left_front, 10);
    lv_obj_set_y(ui_Tire_left_front, -14);
    lv_obj_set_align(ui_Tire_left_front, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Tire_left_front, "2.9");
    lv_obj_set_style_text_color(ui_Tire_left_front, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tire_left_front, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tire_left_front, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tire_left_back = lv_label_create(ui_Tire_pressure);
    lv_obj_set_width(ui_Tire_left_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tire_left_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tire_left_back, 10);
    lv_obj_set_y(ui_Tire_left_back, 11);
    lv_obj_set_align(ui_Tire_left_back, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Tire_left_back, "2.9");
    lv_obj_set_style_text_color(ui_Tire_left_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tire_left_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tire_left_back, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_obj_create(ui_Drive);
    lv_obj_remove_style_all(ui_Temperature);
    lv_obj_set_width(ui_Temperature, 100);
    lv_obj_set_height(ui_Temperature, 50);
    lv_obj_set_x(ui_Temperature, 106);
    lv_obj_set_y(ui_Temperature, 91);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Inside_Temp = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Inside_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Inside_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Inside_Temp, -10);
    lv_obj_set_y(ui_Inside_Temp, -14);
    lv_obj_set_align(ui_Inside_Temp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Inside_Temp, "25 C");
    lv_obj_set_style_text_color(ui_Inside_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Inside_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Inside_Temp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Outside_Temp = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Outside_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Outside_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Outside_Temp, -10);
    lv_obj_set_y(ui_Outside_Temp, 11);
    lv_obj_set_align(ui_Outside_Temp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Outside_Temp, "32 C");
    lv_obj_set_style_text_color(ui_Outside_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Outside_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Outside_Temp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Power_Save_Bar = lv_bar_create(ui_Drive);
    lv_bar_set_mode(ui_Power_Save_Bar, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_Power_Save_Bar, -100, 100);
    lv_bar_set_value(ui_Power_Save_Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Power_Save_Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Power_Save_Bar, 302);
    lv_obj_set_height(ui_Power_Save_Bar, 2);
    lv_obj_set_x(ui_Power_Save_Bar, 0);
    lv_obj_set_y(ui_Power_Save_Bar, 62);
    lv_obj_set_align(ui_Power_Save_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Power_Save_Bar, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Power_Save_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Power_Save_Bar, lv_color_hex(0x00BA11), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Power_Save_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_Drive_screen_destroy(void)
{
    if(ui_Drive) lv_obj_del(ui_Drive);

    // NULL screen variables
    ui_Drive = NULL;
    ui_Speed = NULL;
    ui_Speed_Label = NULL;
    ui_Speed_Unit = NULL;
    ui_FSD_icon = NULL;
    ui_Cargear = NULL;
    ui_Tire_pressure = NULL;
    ui_Tire_Image = NULL;
    ui_Tire_right_front = NULL;
    ui_Tire_right_back = NULL;
    ui_Tire_left_front = NULL;
    ui_Tire_left_back = NULL;
    ui_Temperature = NULL;
    ui_Inside_Temp = NULL;
    ui_Outside_Temp = NULL;
    ui_Power_Save_Bar = NULL;

}
