// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Landing = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Landing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        // 由 main.cpp 数据驱动进行引导和配对控制，删除默认自动跳转
    }
}

// build funtions

void ui_Landing_screen_init(void)
{
    ui_Landing = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Landing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Landing, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Landing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Landing);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -4);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "TESLA");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Landing, ui_event_Landing, LV_EVENT_ALL, NULL);

}

void ui_Landing_screen_destroy(void)
{
    if(ui_Landing) lv_obj_del(ui_Landing);

    // NULL screen variables
    ui_Landing = NULL;
    ui_Label1 = NULL;

}
