// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_LANDING_H
#define UI_LANDING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Landing
extern void ui_Landing_screen_init(void);
extern void ui_Landing_screen_destroy(void);
extern void ui_event_Landing(lv_event_t * e);
extern lv_obj_t * ui_Landing;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

