// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_SCREEN_BLE_CONNECT_H
#define UI_SCREEN_BLE_CONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_BLE_Connect
extern void ui_Screen_BLE_Connect_screen_init(void);
extern void ui_Screen_BLE_Connect_screen_destroy(void);
extern void ui_event_Screen_BLE_Connect(lv_event_t * e);
extern lv_obj_t * ui_Screen_BLE_Connect;
extern lv_obj_t * ui_Landing_Image;
extern lv_obj_t * ui_BLE_Status_Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

