// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_SCREEN_SESSION_SYNC_H
#define UI_SCREEN_SESSION_SYNC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Session_Sync
extern void ui_Screen_Session_Sync_screen_init(void);
extern void ui_Screen_Session_Sync_screen_destroy(void);
extern void ui_event_Screen_Session_Sync(lv_event_t * e);
extern lv_obj_t * ui_Screen_Session_Sync;
extern lv_obj_t * ui_sync_Image;
extern lv_obj_t * ui_loading_animation;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

