// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Screen_Session_Sync = NULL;
lv_obj_t * ui_sync_Image = NULL;
lv_obj_t * ui_loading_animation = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen_Session_Sync_screen_init(void)
{
    ui_Screen_Session_Sync = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Session_Sync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Session_Sync, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Session_Sync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync_Image = lv_img_create(ui_Screen_Session_Sync);
    lv_img_set_src(ui_sync_Image, &ui_img_sync_3_png);
    lv_obj_set_width(ui_sync_Image, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_sync_Image, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_sync_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sync_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sync_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loading_animation = lv_img_create(ui_Screen_Session_Sync);
    lv_img_set_src(ui_loading_animation, &ui_img_loading_png);
    lv_obj_set_width(ui_loading_animation, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_loading_animation, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_loading_animation, 0);
    lv_obj_set_y(ui_loading_animation, 79);
    lv_obj_set_align(ui_loading_animation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading_animation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_loading_animation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen_Session_Sync);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, -96);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SYNC");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen_Session_Sync);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "");

}

void ui_Screen_Session_Sync_screen_destroy(void)
{
    if(ui_Screen_Session_Sync) lv_obj_del(ui_Screen_Session_Sync);

    // NULL screen variables
    ui_Screen_Session_Sync = NULL;
    ui_sync_Image = NULL;
    ui_loading_animation = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;

}
