// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

void ui_comp_Alarm_Comp_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Clock_Dot_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Scrolldots_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Small_Label_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Cargear_create_hook(lv_obj_t * comp)
{
}
