// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef _ESP32_TFT_LGVL_GUI_UI_COMP_HOOK_H
#define _ESP32_TFT_LGVL_GUI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Cargear_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
