// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Screen_Session_Sync = NULL;
lv_obj_t * ui_sync_Image = NULL;
lv_obj_t * ui_loading_animation = NULL;
// event funtions
void ui_event_Screen_Session_Sync(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen_Session_Sync, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_Screen_Session_Sync_screen_init);
    }
}

// build funtions

void ui_Screen_Session_Sync_screen_init(void)
{
    ui_Screen_Session_Sync = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Session_Sync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Session_Sync, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Session_Sync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync_Image = lv_img_create(ui_Screen_Session_Sync);
    lv_img_set_src(ui_sync_Image, &ui_img_sync_png);
    lv_obj_set_width(ui_sync_Image, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_sync_Image, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_sync_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sync_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sync_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loading_animation = lv_img_create(ui_Screen_Session_Sync);
    lv_img_set_src(ui_loading_animation, &ui_img_loading_png);
    lv_obj_set_width(ui_loading_animation, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_loading_animation, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_loading_animation, 0);
    lv_obj_set_y(ui_loading_animation, 79);
    lv_obj_set_align(ui_loading_animation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading_animation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_loading_animation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen_Session_Sync, ui_event_Screen_Session_Sync, LV_EVENT_ALL, NULL);

}

void ui_Screen_Session_Sync_screen_destroy(void)
{
    if(ui_Screen_Session_Sync) lv_obj_del(ui_Screen_Session_Sync);

    // NULL screen variables
    ui_Screen_Session_Sync = NULL;
    ui_sync_Image = NULL;
    ui_loading_animation = NULL;

}
