// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef UI_SCREEN_KEYCARD_PAIR_H
#define UI_SCREEN_KEYCARD_PAIR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Keycard_Pair
extern void ui_Screen_Keycard_Pair_screen_init(void);
extern void ui_Screen_Keycard_Pair_screen_destroy(void);
extern void ui_event_Screen_Keycard_Pair(lv_event_t * e);
extern lv_obj_t * ui_Screen_Keycard_Pair;
extern lv_obj_t * ui_keycard_image;
extern lv_obj_t * ui_Pair_Status;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

