// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#include "../ui.h"

lv_obj_t * ui_Screen_Keycard_Pair = NULL;
lv_obj_t * ui_keycard_image = NULL;
lv_obj_t * ui_Pair_Status = NULL;
// event funtions
void ui_event_Screen_Keycard_Pair(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen_Keycard_Pair, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_Screen_Keycard_Pair_screen_init);
    }
}

// build funtions

void ui_Screen_Keycard_Pair_screen_init(void)
{
    ui_Screen_Keycard_Pair = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Keycard_Pair, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Keycard_Pair, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Keycard_Pair, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keycard_image = lv_img_create(ui_Screen_Keycard_Pair);
    lv_img_set_src(ui_keycard_image, &ui_img_keycard_png);
    lv_obj_set_width(ui_keycard_image, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_keycard_image, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_keycard_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_keycard_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_keycard_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pair_Status = lv_label_create(ui_Screen_Keycard_Pair);
    lv_obj_set_width(ui_Pair_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pair_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pair_Status, 0);
    lv_obj_set_y(ui_Pair_Status, 92);
    lv_obj_set_align(ui_Pair_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pair_Status, "Waiting for card...");
    lv_obj_set_style_text_color(ui_Pair_Status, lv_color_hex(0xA2A2A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pair_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pair_Status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Keycard_Pair, ui_event_Screen_Keycard_Pair, LV_EVENT_ALL, NULL);

}

void ui_Screen_Keycard_Pair_screen_destroy(void)
{
    if(ui_Screen_Keycard_Pair) lv_obj_del(ui_Screen_Keycard_Pair);

    // NULL screen variables
    ui_Screen_Keycard_Pair = NULL;
    ui_keycard_image = NULL;
    ui_Pair_Status = NULL;

}
