// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESP32_TFT_LGVL_GUI

#ifndef _ESP32_TFT_LGVL_GUI_UI_H
#define _ESP32_TFT_LGVL_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_BLE_Connect.h"
#include "screens/ui_Screen_Keycard_Pair.h"
#include "screens/ui_Screen_Session_Sync.h"
#include "screens/ui_Drive.h"
#include "screens/ui_Charge.h"
#include "screens/ui_Door_open.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * chargepower_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * dooropen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * loading_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_landing_png);    // assets/landing.png
LV_IMG_DECLARE(ui_img_keycard_png);    // assets/KeyCard.png
LV_IMG_DECLARE(ui_img_sync_png);    // assets/sync.png
LV_IMG_DECLARE(ui_img_loading_png);    // assets/loading.png
LV_IMG_DECLARE(ui_img_fsd_png);    // assets/FSD.png
LV_IMG_DECLARE(ui_img_car1_png);    // assets/car1.png
LV_IMG_DECLARE(ui_img_charger_power_png);    // assets/charger_power.png
LV_IMG_DECLARE(ui_img_509039616);    // assets/特斯拉充电.png
LV_IMG_DECLARE(ui_img_door_open_png);    // assets/door_open.png
LV_IMG_DECLARE(ui_img_door_open_alarm_png);    // assets/door_open_alarm.png

// FONTS
LV_FONT_DECLARE(ui_font_google_sans);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Number_small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
